### ISSUE TITLE
Issue with latest version of python?

### ISSUE THREAD

**Issue by mbyott** [BWH-Lichterfeld-Lab/Intactness-Pipeline#1]
Hi, thanks for writing this brilliant intactness pipeline.

I've had some trouble getting it to work and I think it's due to python incompatibility.

```
Invalid command line
Unknown option in

2023-09-06 15:53:04,798         pipe.gag_codon          Running codon analysis
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/c/Users/mbyot/Desktop/kath.results/Intactness-Pipeline-master/intactness/__main__.py", line 45, in <module>
    gag_codon(cfg['Codon'], seqs)
  File "/mnt/c/Users/mbyot/Desktop/kath.results/Intactness-Pipeline-master/intactness/gag_codon.py", line 32, in gag_codon
    recs = SeqIO.parse(file_aln, 'fasta')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cloud/miniconda3/envs/intactness/lib/python3.11/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cloud/miniconda3/envs/intactness/lib/python3.11/site-packages/Bio/SeqIO/FastaIO.py", line 223, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/cloud/miniconda3/envs/intactness/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py", line 45, in __init__
    self.stream = open(source, "r" + mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/seqs/muscle_alignment.fasta'
```

This is the error I get, I have previously (last yerar) run this pipeline with no issues, but after installing it on a new system I now get errors. Any ideas?

Cheers.

**Comment by gaoce** [comment]
Hi,

It seems that alignment results from the previous step (muscle alignment) are missing. One possible reason is that all your input are large deletion or internal inversion, so that they are filtered out. Hope this helps.

Thanks.
Charlie

**Comment by clarkmu** [comment]
This issue comes from using Muscle version 5.  Downgrade to Muscle 3.8
